services:
  app:
    build: .
    container_name: tkinter-app-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./lung.spec:/app/lung.spec
      - ./out:/app/out
      - ./out/dist:/app/dist
      - ./out/build:/app/build
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    network_mode: host
    stdin_open: true
    tty: true

  shell:
    build: .
    container_name: tkinter-app-shell
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./lung.spec:/app/lung.spec
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
    network_mode: host
    stdin_open: true
    tty: true
    command: /bin/bash
